# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3aae67aa2a7daf3980df2a18c40a65c3b5410e34a288655120cf2460648aa34581333283440bbb5d9aef4a754ed7274fc57d80f56c5d8559c6c5243983e3ead

test:
  secret_key_base: 4d4924e9fe5fa4099c5d2dea726d7548fa4c33b2d21fcc450ab69f03191924a6888032282a1be8f5d9f30fbc55e8c1dd9471e2ed36fff97e41d2307d5f08009c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
